# Evaluación de Modelos

En esta etapa se analizará el rendimiento de los modelos entrenados durante la fase de modelado.

Dado que se trata de un problema de clasificación altamente desbalanceado, la Accuracy no será la métrica principal de evaluación. En su lugar, se utilizarán métricas más adecuadas para la detección de fraude, como Recall, Precision, F1-score, ROC-AUC y PR-AUC.

Finalmente, se realizará una comparación entre los modelos entrenados para seleccionar la alternativa con mejor desempeño.

## Recall

Recall mide la capacidad de un modelo para detectar correctamente las transacciones fraudulentas.

Esta métrica responde a la siguiente pregunta:

> De todos los fraudes reales, ¿cuántos logró identificar el modelo?

En problemas de detección de fraude, Recall suele ser una de las métricas más importantes, ya que un bajo Recall implica dejar pasar transacciones fraudulentas sin detectar.

In [2]:
import pandas as pd

In [3]:
recall_df = pd.DataFrame({
    "Modelo": ["Logistic Regression", "Random Forest", "XGBoost"],
    "Recall": [0.58, 0.73, 0.69]
})

recall_df

,Modelo,Recall
0,Logistic Regression,0.58
1,Random Forest,0.73
2,XGBoost,0.69


### Interpretación

Los resultados muestran diferencias claras entre los modelos evaluados.

Random Forest obtuvo el Recall más alto (73%), logrando detectar la mayor proporción de transacciones fraudulentas presentes en el conjunto de prueba.

XGBoost alcanzó un Recall del 69%, mostrando también una buena capacidad de detección, aunque ligeramente inferior a Random Forest.

Por su parte, Logistic Regression obtuvo el menor Recall (58%), dejando sin detectar una mayor cantidad de fraudes.

Dado que el objetivo principal del proyecto es identificar transacciones fraudulentas, Random Forest presenta el mejor desempeño según esta métrica.

## Precision

Precision mide la proporción de transacciones identificadas como fraude que realmente corresponden a fraudes.

Esta métrica responde a la siguiente pregunta:

> De todas las transacciones que el modelo clasificó como fraude, ¿cuántas eran realmente fraudulentas?

Una Precision elevada indica que el modelo genera pocas falsas alarmas, evitando clasificar incorrectamente transacciones legítimas como fraudulentas.

In [4]:
precision_df = pd.DataFrame({
    "Modelo": ["Logistic Regression", "Random Forest", "XGBoost"],
    "Precision": [0.85, 0.97, 0.75]
})

precision_df

,Modelo,Precision
0,Logistic Regression,0.85
1,Random Forest,0.97
2,XGBoost,0.75


### Interpretación

Random Forest obtuvo la Precision más alta (97%), lo que indica que la gran mayoría de las transacciones clasificadas como fraude eran realmente fraudulentas.

Logistic Regression alcanzó una Precision del 85%, mostrando también una baja proporción de falsas alarmas.

Por su parte, XGBoost obtuvo una Precision del 75%, siendo el modelo con peor desempeño en esta métrica debido a una mayor cantidad de falsos positivos.

Dado que una Precision elevada reduce el número de transacciones legítimas clasificadas erróneamente como fraude, Random Forest vuelve a posicionarse como el modelo con mejor rendimiento.

## F1-Score

El F1-score combina Precision y Recall en una única métrica, proporcionando una medida equilibrada del rendimiento del modelo.

Esta métrica resulta especialmente útil en problemas de clasificación desbalanceada, donde es importante detectar la mayor cantidad posible de fraudes sin generar un número excesivo de falsas alarmas.

In [5]:
f1_df = pd.DataFrame({
    "Modelo": ["Logistic Regression", "Random Forest", "XGBoost"],
    "F1-Score": [0.69, 0.83, 0.72]
})

f1_df

,Modelo,F1-Score
0,Logistic Regression,0.69
1,Random Forest,0.83
2,XGBoost,0.72


### Interpretación

Random Forest obtuvo el F1-score más alto (83%), reflejando el mejor equilibrio entre Precision y Recall.

XGBoost alcanzó un F1-score del 72%, mostrando un rendimiento intermedio entre los modelos evaluados.

Logistic Regression obtuvo el F1-score más bajo (69%), debido principalmente a su menor capacidad para detectar fraudes.

Considerando simultáneamente la capacidad de detección de fraude y la reducción de falsas alarmas, Random Forest presenta nuevamente el mejor desempeño global.

In [6]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import auc

## ROC-AUC

ROC-AUC (Receiver Operating Characteristic - Area Under the Curve) mide la capacidad del modelo para distinguir entre las clases positiva y negativa a distintos umbrales de decisión.

Un valor cercano a 1 indica una excelente capacidad de discriminación, mientras que un valor cercano a 0.5 indica un rendimiento similar al azar.

In [9]:
%run 04_modeling.ipynb

(283726, 30)
(283726,)
X_train: (226980, 30)
X_test: (56746, 30)
y_train: (226980,)
y_test: (56746,)
Original
Class
0    0.998333
1    0.001667
Name: proportion, dtype: float64

Train
Class
0    0.998335
1    0.001665
Name: proportion, dtype: float64

Test
Class
0    0.998326
1    0.001674
Name: proportion, dtype: float64
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.85      0.58      0.69        95

    accuracy                           1.00     56746
   macro avg       0.92      0.79      0.84     56746
weighted avg       1.00      1.00      1.00     56746

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.97      0.73      0.83        95

    accuracy                           1.00     56746
   macro avg       0.99      0.86      0.92     56746
weighted avg       1.00      1.00      1.00     56746




[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.75      0.69      0.72        95

    accuracy                           1.00     56746
   macro avg       0.87      0.85      0.86     56746
weighted avg       1.00      1.00      1.00     56746



In [10]:
y_prob_lr = modelo_lr.predict_proba(X_test)[:, 1]
y_prob_rf = modelo_rf.predict_proba(X_test)[:, 1]
y_prob_xgb = modelo_xgb.predict_proba(X_test)[:, 1]

roc_auc_df = pd.DataFrame({
    "Modelo": ["Logistic Regression", "Random Forest", "XGBoost"],
    "ROC-AUC": [
        roc_auc_score(y_test, y_prob_lr),
        roc_auc_score(y_test, y_prob_rf),
        roc_auc_score(y_test, y_prob_xgb)
    ]
})

roc_auc_df

,Modelo,ROC-AUC
0,Logistic Regression,0.953089
1,Random Forest,0.923946
2,XGBoost,0.857463


### Interpretación

Logistic Regression obtuvo el mayor valor de ROC-AUC (0.953), mostrando la mejor capacidad para separar transacciones fraudulentas y legítimas a distintos umbrales de decisión.

Random Forest alcanzó un ROC-AUC de 0.924, manteniendo también una excelente capacidad de discriminación entre clases.

XGBoost obtuvo el valor más bajo (0.857), aunque continúa mostrando un rendimiento claramente superior al azar.

Estos resultados indican que Logistic Regression genera las probabilidades más consistentes para diferenciar ambas clases. Sin embargo, como se observó en las métricas de Recall, Precision y F1-score, esto no implica necesariamente que sea el mejor modelo para la detección de fraude en términos operativos.

## PR-AUC

PR-AUC (Precision-Recall Area Under the Curve) evalúa el equilibrio entre Precision y Recall para distintos umbrales de decisión.

Esta métrica resulta especialmente útil en problemas con clases altamente desbalanceadas, como la detección de fraude, donde la clase positiva representa una proporción muy pequeña del total de observaciones.

A diferencia de ROC-AUC, PR-AUC se centra específicamente en el rendimiento sobre la clase positiva, proporcionando una evaluación más exigente de la capacidad del modelo para detectar fraudes.

In [11]:
precision_lr, recall_lr, _ = precision_recall_curve(y_test, y_prob_lr)
precision_rf, recall_rf, _ = precision_recall_curve(y_test, y_prob_rf)
precision_xgb, recall_xgb, _ = precision_recall_curve(y_test, y_prob_xgb)

pr_auc_df = pd.DataFrame({
    "Modelo": ["Logistic Regression", "Random Forest", "XGBoost"],
    "PR-AUC": [
        auc(recall_lr, precision_lr),
        auc(recall_rf, precision_rf),
        auc(recall_xgb, precision_xgb)
    ]
})

pr_auc_df

,Modelo,PR-AUC
0,Logistic Regression,0.689521
1,Random Forest,0.796741
2,XGBoost,0.694158


### Interpretación

Random Forest obtuvo el mayor valor de PR-AUC (0.797), mostrando el mejor equilibrio entre Precision y Recall a distintos umbrales de decisión.

XGBoost alcanzó un valor de 0.694, mientras que Logistic Regression obtuvo 0.690, presentando resultados muy similares entre sí.

Dado que el problema de detección de fraude presenta una fuerte desproporción entre clases, PR-AUC constituye una métrica especialmente relevante. En este contexto, Random Forest vuelve a destacar como el modelo con mejor desempeño global.

## Comparación de Modelos

Para comparar el rendimiento global de los modelos entrenados, se recopilaron las principales métricas de evaluación obtenidas durante el análisis.

Las métricas consideradas fueron Recall, Precision, F1-score, ROC-AUC y PR-AUC.

In [12]:
comparacion_df = pd.DataFrame({
    "Modelo": ["Logistic Regression", "Random Forest", "XGBoost"],
    "Recall": [0.58, 0.73, 0.69],
    "Precision": [0.85, 0.97, 0.75],
    "F1-Score": [0.69, 0.83, 0.72],
    "ROC-AUC": [0.953, 0.924, 0.857],
    "PR-AUC": [0.690, 0.797, 0.694]
})

comparacion_df

,Modelo,Recall,Precision,F1-Score,ROC-AUC,PR-AUC
0,Logistic Regression,0.58,0.85,0.69,0.953,0.690
1,Random Forest,0.73,0.97,0.83,0.924,0.797
2,XGBoost,0.69,0.75,0.72,0.857,0.694


### Conclusiones

Durante la fase de evaluación se analizaron diferentes métricas con el objetivo de comparar el rendimiento de los modelos entrenados para la detección de fraude.

Debido al fuerte desbalance existente en el dataset, la Accuracy no fue considerada como la métrica principal de evaluación. En su lugar, se utilizaron métricas más adecuadas para este tipo de problemas, como Recall, Precision, F1-score, ROC-AUC y PR-AUC.

Los resultados obtenidos muestran que Random Forest fue el modelo con mejor desempeño global. Este modelo alcanzó el mayor Recall (73%), logrando detectar la mayor proporción de transacciones fraudulentas presentes en el conjunto de prueba. Además, obtuvo una Precision del 97%, minimizando la cantidad de falsas alarmas y reduciendo significativamente el número de transacciones legítimas clasificadas incorrectamente como fraude.

Si bien Logistic Regression obtuvo el mejor resultado en ROC-AUC (0.953), Random Forest superó al resto de modelos en las métricas más relevantes para un problema de detección de fraude, incluyendo Precision, Recall, F1-score y PR-AUC.

Por su parte, XGBoost mostró un rendimiento sólido y competitivo, aunque no logró superar a Random Forest en ninguna de las métricas principales consideradas durante la evaluación.

En conjunto, los resultados indican que Random Forest ofrece el mejor equilibrio entre capacidad de detección de fraude y control de falsos positivos, convirtiéndose en la alternativa más adecuada para su utilización en un entorno productivo.

Por este motivo, Random Forest fue seleccionado como modelo final del proyecto y será utilizado durante la fase de producción para la construcción del pipeline de inferencia, la API de predicción y su posterior despliegue.